<a href="https://colab.research.google.com/github/Pitchanuj/data-science-bootcamp-12/blob/main/Python/HW_API_to_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **HW4: Get Data From API**

We will get Disney character data from https://disneyapi.dev/ and convert into DataFrame

In [2]:
# import library
import requests
import numpy as np
import pandas as pd

In [3]:
url = "https://api.disneyapi.dev/character"

response = requests.get(url)
response

In [4]:
response_json = response.json()
page = response_json['info']["totalPages"]
page

197

In [5]:
characters = []
for i in range(page):
    url = f"https://api.disneyapi.dev/character?page={i+1}"
    response = requests.get(url).json()
    for character in response["data"]:
        data = [character["_id"],
            character["name"],
            ", ".join(character["films"]) if len(character["films"]) > 0 else np.nan,
            ", ".join(character["shortFilms"]) if len(character["shortFilms"]) > 0 else np.nan,
            ", ".join(character["tvShows"]) if len(character["tvShows"]) > 0 else np.nan,
            ", ".join(character["videoGames"]) if len(character["videoGames"]) > 0 else np.nan,
            len(character["films"]) + len(character["shortFilms"]) + len(character["tvShows"]) + len(character["videoGames"])]
        characters.append(data)

In [6]:
characters_df = pd.DataFrame(characters, columns=["id", "name", "films", "shortFilms", "tvShows", "videoGames", "total_appearance"])
characters_df.head(10)

,id,name,films,shortFilms,tvShows,videoGames,total_appearance
0,112,Achilles,Hercules (film),NaN,Hercules (TV series),Kingdom Hearts III,3
1,18,Abigail the Cow,"The Fox and the Hound, The Fox and the Hound 2",NaN,NaN,NaN,2
2,16,Abdullah,Cheetah,NaN,NaN,NaN,1
3,45,Admiral Boom and Mr. Binnacle,"Mary Poppins (film), Mary Poppins Returns",NaN,NaN,NaN,2
4,7,.GIFfany,NaN,NaN,Gravity Falls,Disney Heroes: Battle Mode,2
5,12,90's Adventure Bear,NaN,NaN,Pickle and Peanut,NaN,1
6,36,Candace Adams,NaN,NaN,K.C. Undercover,NaN,1
7,139,Ahadi,"The Lion King, The Lion King (2019 film)",NaN,NaN,NaN,2
8,152,Al Muddy Sultan,NaN,NaN,Aladdin (TV series),NaN,1
9,181,Irwina Allen,NaN,NaN,Chip 'n Dale Rescue Rangers,NaN,1

In [7]:
characters_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9821 entries, 0 to 9820
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                9821 non-null   int64
 1   name              9821 non-null   object
 2   films             4348 non-null   object
 3   shortFilms        1049 non-null   object
 4   tvShows           5734 non-null   object
 5   videoGames        1731 non-null   object
 6   total_appearance  9821 non-null   int64
dtypes: int64(2), object(5)
memory usage: 537.2+ KB

In [ ]:
# write to csv
characters_df.to_csv("disney_characters.csv", index = False)

List the characters with the highest number of appearances on screen media

In [8]:
top_media_character = characters_df[["name", "total_appearance"]].sort_values("total_appearance", ascending = False).head(10)
top_media_character = top_media_character.reset_index(drop = True)
top_media_character

                  name  total_appearance
0          Donald Duck                86
1                Goofy                73
2         Mickey Mouse                64
3  The How-to Narrator                59
4           Daisy Duck                58
5                 Pete                55
6       Scrooge McDuck                54
7      Winnie the Pooh                54
8                Pluto                53
9               Tigger                52

How many characters have never appeared on screen

In [9]:
zero_appearances = characters_df[characters_df['total_appearance'] == 0]
zero_appearances.shape[0]

768